framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: followup_app

        # Cache par défaut (overridé en dev/prod)
        app: cache.adapter.filesystem

# -----------------------------------------------
# PRODUCTION : Redis cache
# -----------------------------------------------
when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: '%env(REDIS_URL)%'
            
            pools:
                # Cache pour les sessions
                cache.sessions:
                    adapter: cache.adapter.redis
                    provider: '%env(REDIS_URL)%'
