services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: followup-php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80" # accès Symfony via http://localhost:8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: followup-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-follow_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-followup_db}
      TZ: ${TZ:-Europe/Paris}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: followup-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    ports:
      - "8081:80" # accès pgAdmin via http://localhost:8081
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: followup-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: followup-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Interface web
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  pgadmin_data:
