# Configuration DEV : override pour utiliser fichiers au lieu de Redis
framework:
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'